service: sls-puppeteer-js
frameworkVersion: '3'
useDotenv: true # Load .env file

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1
  provider:

functions:
  index:
    handler: src/index.handler
    timeout: 180 # 3 minutes
    memorySize: 2048
